# Generated by Django 4.2 on 2023-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_allow_date_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
