# Generated by Django 4.2 on 2023-12-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_allow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
