# Generated by Django 4.2 on 2023-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_defaultnetwork_params_modelparam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefaultparam',
            name='choices_values',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
