# Generated by Django 4.2 on 2023-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_modeldefaultparam_value_alter_modelparam_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='networks',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
