# Generated by Django 4.2 on 2023-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_networks_path_alter_networks_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='networks',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
