# Generated by Django 4.2 on 2023-09-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_networks_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='main.dataset')),
            ],
        ),
        migrations.RemoveField(
            model_name='modeldefaultparam',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelparam',
            name='model',
        ),
        migrations.RemoveField(
            model_name='networks',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='networks',
            name='default_model',
        ),
        migrations.DeleteModel(
            name='DefaultNetwork',
        ),
        migrations.DeleteModel(
            name='ModelDefaultParam',
        ),
        migrations.DeleteModel(
            name='ModelParam',
        ),
        migrations.DeleteModel(
            name='Networks',
        ),
    ]
