# Generated by Django 4.2 on 2023-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dataset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmodel',
            name='configs',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='learnmodel',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
