# Generated by Django 4.2 on 2023-09-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_learnmodel_dataset_learnmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learnmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', related_query_name='models', to=settings.AUTH_USER_MODEL),
        ),
    ]
