# Generated by Django 5.0.4 on 2024-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Классификация'), (2, 'Регрессия')], default=1),
        ),
    ]
